# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3e71f1d21acff1d68cfe34bcb942cdfcdd6a4e777952d65801c865168600f3880a27ba5ee29f9514b829e343d443e4ac9689ebcf78555581d039064468e65c

test:
  secret_key_base: 7779449717e22d602f5c05cb211337d51fa60d42db08b8718c315a5cf6fe449cbddd55fb93d8057a11f9771d8142403f3852d183f3d7a53f915bf3f2cb13df83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
